const fs = require("fs");
const path = "d:/SEKOLAH/wahyu-project/src/app/(dashboard)/absensi/page.tsx";

const content = [
  '"use client";',
  '',
  'import { useState } from "react";',
  'import { CalendarCheck, ClipboardCheck, UserX, Clock, Search, Filter } from "lucide-react";',
  'import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";',
  'import { Button } from "@/components/ui/button";',
  'import { Input } from "@/components/ui/input";',
  'import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";',
  'import { Avatar, AvatarFallback } from "@/components/ui/avatar";',
  'import { StatCard } from "@/components/shared/stat-card";',
  'import { PageHeader } from "@/components/shared/page-header";',
  'import { StatusBadge } from "@/components/shared/status-badge";',
  'import { cn } from "@/lib/utils";',
  '',
  'const todaySchedules = [',
  '  { id: "s1", name: "Smash Accuracy & Power", time: "08:00 - 09:30", venue: "Court A", coach: "Coach Peter Gade" },',
  '  { id: "s2", name: "Endurance Circuit", time: "10:00 - 11:15", venue: "Gym", coach: "Coach Taufik" },',
  '];',
  '',
  'const athletes = [',
  '  { id: "1", name: "Marcus Fernaldi", category: "Senior", currentStatus: null as string | null },',
  '  { id: "2", name: "Gregoria Mariska", category: "Senior", currentStatus: null as string | null },',
  '  { id: "3", name: "Alwi Farhan", category: "Junior", currentStatus: null as string | null },',
  '  { id: "4", name: "Mutiara Ayu", category: "Junior", currentStatus: null as string | null },',
  '  { id: "5", name: "Leo Rolly", category: "Senior", currentStatus: null as string | null },',
  '  { id: "6", name: "Rinov Rivaldy", category: "Senior", currentStatus: null as string | null },',
  '  { id: "7", name: "Putri Kusuma", category: "Junior", currentStatus: null as string | null },',
  '  { id: "8", name: "Fikri Ahmad", category: "Junior", currentStatus: null as string | null },',
  '];',
  '',
  'const attendanceHistory = [',
  '  { date: "23 Oct 2023", program: "Doubles Rotation", athlete: "Marcus Fernaldi", status: "Hadir", markedBy: "Coach Peter Gade" },',
  '  { date: "23 Oct 2023", program: "Doubles Rotation", athlete: "Kevin Sanjaya", status: "Hadir", markedBy: "Coach Peter Gade" },',
  '  { date: "22 Oct 2023", program: "Net Play Mastery", athlete: "Alwi Farhan", status: "Izin", markedBy: "Coach Liliyana" },',
  '  { date: "22 Oct 2023", program: "Net Play Mastery", athlete: "Mutiara Ayu", status: "Hadir", markedBy: "Coach Liliyana" },',
  '  { date: "21 Oct 2023", program: "Endurance Circuit", athlete: "Leo Rolly", status: "Tidak Hadir", markedBy: "Coach Taufik" },',
  '  { date: "21 Oct 2023", program: "Endurance Circuit", athlete: "Marcus Fernaldi", status: "Hadir", markedBy: "Coach Taufik" },',
  '  { date: "20 Oct 2023", program: "Smash Accuracy", athlete: "Gregoria Mariska", status: "Hadir", markedBy: "Coach Peter Gade" },',
  '  { date: "20 Oct 2023", program: "Smash Accuracy", athlete: "Rinov Rivaldy", status: "Hadir", markedBy: "Coach Peter Gade" },',
  '];',
  '',
  'const statusOptions = ["Hadir", "Izin", "Tidak Hadir"] as const;',
  '',
  'export default function AbsensiPage() {',
  '  const [selectedSchedule, setSelectedSchedule] = useState(todaySchedules[0].id);',
  '  const [attendanceData, setAttendanceData] = useState<Record<string, string>>({});',
  '',
  '  const markAttendance = (athleteId: string, status: string) => {',
  '    setAttendanceData((prev) => ({ ...prev, [athleteId]: status }));',
  '  };',
  '',
  '  const markedCount = Object.keys(attendanceData).length;',
  '  const hadirCount = Object.values(attendanceData).filter((s) => s === "Hadir").length;',
  '  const izinCount = Object.values(attendanceData).filter((s) => s === "Izin").length;',
  '  const absentCount = Object.values(attendanceData).filter((s) => s === "Tidak Hadir").length;',
  '',
  '  return (',
  '    <div className="space-y-6">',
  '      <PageHeader',
  '        title="Absensi Latihan"',
  '        description="Mark attendance for today&#39;s training sessions and view attendance history."',
  '      />',
  '',
  '      {/* Stats Cards */}',
  '      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">',
  '        <StatCard title="Total Sessions (Month)" value={24} icon={CalendarCheck} />',
  '        <StatCard title="Avg Attendance" value="92.5%" icon={ClipboardCheck} change="+3.2%" changeType="up" iconColor="text-green-400" />',
  '        <StatCard title="Absent Today" value={absentCount} icon={UserX} iconColor="text-red-400" />',
  '        <StatCard title="Pending Mark" value={athletes.length - markedCount} icon={Clock} iconColor="text-yellow-400" />',
  '      </div>',
  '',
  '      {/* Mark Attendance Section */}',
  '      <Card className="border-border bg-card">',
  '        <CardHeader>',
  '          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">',
  '            <CardTitle className="text-lg">Mark Attendance - Today</CardTitle>',
  '            <Select value={selectedSchedule} onValueChange={setSelectedSchedule}>',
  '              <SelectTrigger className="w-full sm:w-72 bg-secondary border-border">',
  '                <SelectValue />',
  '              </SelectTrigger>',
  '              <SelectContent className="bg-card border-border">',
  '                {todaySchedules.map((s) => (',
  '                  <SelectItem key={s.id} value={s.id}>',
  '                    {s.name} ({s.time})',
  '                  </SelectItem>',
  '                ))}',
  '              </SelectContent>',
  '            </Select>',
  '          </div>',
  '          <div className="flex items-center gap-4 text-sm text-muted-foreground mt-2">',
  '            <span className="flex items-center gap-1.5"><Clock className="h-3.5 w-3.5" />{todaySchedules.find(s => s.id === selectedSchedule)?.time}</span>',
  '            <span>{todaySchedules.find(s => s.id === selectedSchedule)?.venue}</span>',
  '            <span>{todaySchedules.find(s => s.id === selectedSchedule)?.coach}</span>',
  '          </div>',
  '        </CardHeader>',
  '        <CardContent>',
  '          <div className="space-y-2">',
  '            {athletes.map((athlete) => (',
  '              <div',
  '                key={athlete.id}',
  '                className="flex items-center justify-between p-3 rounded-lg bg-secondary/30 hover:bg-secondary/50 transition-colors"',
  '              >',
  '                <div className="flex items-center gap-3">',
  '                  <Avatar className="h-9 w-9">',
  '                    <AvatarFallback className="bg-primary/10 text-primary text-xs">',
  '                      {athlete.name.split(" ").map((n) => n[0]).join("")}',
  '                    </AvatarFallback>',
  '                  </Avatar>',
  '                  <div>',
  '                    <p className="text-sm font-medium text-foreground">{athlete.name}</p>',
  '                    <p className="text-xs text-muted-foreground">{athlete.category}</p>
